name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: npm ci
      - run: npm run build-ci
      - run: npm run test-ci
      - run: npm run test-ci-jest

      - if: ${{ github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' }}
        run: npm pack
      - if: ${{ github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' }}
        name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "./*.tgz"

  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./
      - run: ls -lah
      - run: tar xzvf *.tgz
      - run: |
          cd package
          npm set-script prepare ""
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: package/package.json
          token: ${{ secrets.NPM_TOKEN }}
